<a href="https://colab.research.google.com/github/NatalhyBB/EjerciciosPropuestos/blob/main/Ejercicios_Propuestos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIOS PROPUESTOS

Ejercicio 1:
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la muestre por pantalla.

In [107]:
cursos = []
num_cursos = int(input("Ingrese el numero de cursos: "))

for i in range (1, num_cursos+1):
  curso = input(f"Ingrese la asignatura {i}: ")
  cursos.append(curso)

print ("\nLos cursos son:" , cursos)
print ("\nLos cursos son:")
for curso in cursos:
  print(f"- ", curso)


Ingrese el numero de cursos: 2
Ingrese la asignatura 1: 2
Ingrese la asignatura 2: 2

Los cursos son: ['2', '2']

Los cursos son:
-  2
-  2


Ejercicio 2:
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la muestre por pantalla el mensaje Yo estudio <asignatura>, donde <asignatura> es cada una de las asignaturas de la lista.

In [109]:
cursos=[]
num_cursos = int(input("Ingrese el número de cursos: "))

for i in range (1, num_cursos+1):
  curso = input(f"Ingrese el nombre del curso {i}: ")
  cursos.append(curso)

print("\n")
for curso in cursos:
  print(f"Yo estudio {curso}")

Ingrese el número de cursos: 2
Ingrese el nombre del curso 1: comunicacion
Ingrese el nombre del curso 2: fisica


Yo estudio comunicacion
Yo estudio fisica


Ejercicio 3:
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada asignatura, y después las muestre por pantalla con el mensaje: En 'asignatura' has sacado 'nota' donde 'asignatura' es cada una des las asignaturas de la lista y 'nota' cada una de las correspondientes notas introducidas por el usuario.

In [110]:
import pandas as pd
cursos = []
notas = []
num_cursos = int(input("Ingrese el numero de cursos: "))

for i in range (1, num_cursos + 1):
  curso = input(f"Ingrese el nombre de la asignatura {i}:")
  cursos.append(curso)

for i in range (1, num_cursos + 1):
  nota = int(input(f"Ingrese la nota del curso '{cursos[i-1]}': "))
  notas.append(nota)

df = pd.DataFrame(
    {
        "Curso": cursos,
        "Nota": notas
    }
)
print("\n", df.to_string(index=False) ,"\n")

for i in range (0, num_cursos):
  print (f"En {cursos[i]}  has sacado {notas[i]}")


Ingrese el numero de cursos: 2
Ingrese el nombre de la asignatura 1:matematica
Ingrese el nombre de la asignatura 2:quimica
Ingrese la nota del curso 'matematica': 12
Ingrese la nota del curso 'quimica': 09

      Curso  Nota
matematica    12
   quimica     9 

En matematica  has sacado 12
En quimica  has sacado 9


Ejercicio 4:
Escribir un programa que pregunte al usuario los números ganadores de la lotería primitiva, los almacene en una lista y los muestre por pantalla ordenados de menor a mayor.

In [111]:
import pandas as pd
num_ganadores = []

for i in range (1 , 7):
  numeros = int(input(f"Ingrese el numero ganador {i}: "))
  num_ganadores.append(numeros)

df = pd.DataFrame({
    "Ganadores" : num_ganadores,
    "Ascendente" : sorted(num_ganadores, reverse=False),
    "Descendente" : sorted(num_ganadores, reverse=True)
})

df_centrado = df.apply(lambda col: col.map(lambda x:f"{x:^10}"))

print("\n")
print(df_centrado.to_string(index=False))





Ingrese el numero ganador 1: 4
Ingrese el numero ganador 2: 5
Ingrese el numero ganador 3: 6
Ingrese el numero ganador 4: 7
Ingrese el numero ganador 5: 8
Ingrese el numero ganador 6: 4


 Ganadores Ascendente Descendente
    4          4           8     
    5          4           7     
    6          5           6     
    7          6           5     
    8          7           4     
    4          8           4     


Ejercicio 5:
Escribir un programa que almacene en una lista los números del 1 al 10 y los muestre por pantalla en orden inverso separados por comas.

In [112]:
numeros = list(range(1, 11))

print ("\nNumeros del 1 al 10: \n")
print (" , ".join(map(str, numeros)))
print ("\n Numeros en orden inverso: \n")
ordenados = sorted(numeros, reverse=True)
print (" , ".join(map(str, ordenados)))



Numeros del 1 al 10: 

1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10

 Numeros en orden inverso: 

10 , 9 , 8 , 7 , 6 , 5 , 4 , 3 , 2 , 1


Ejercicio 6:
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada asignatura y elimine de la lista las asignaturas aprobadas. Al final el programa debe mostrar por pantalla las asignaturas que el usuario tiene que repetir.

In [113]:
import pandas as pd
cursos = []
notas = []
num_cursos = int(input("Indique el numero de cursos que lleva: "))

for i in range(1, num_cursos + 1):
  curso=input(f"Ingrese el nombre del curso {i}: ")
  cursos.append(curso)
for i in range (1, num_cursos + 1):
  nota = float(input(f"Ingrese su nota de curso '{cursos[i-1]}': "))
  notas.append(nota)

df = pd.DataFrame({
    "Curso" : cursos,
    "Nota" : notas
})

desaprobado = df[df["Nota"] < 12]
print("\nCursos desaprobados")
print(desaprobado.to_string(index=False))

Indique el numero de cursos que lleva: 3
Ingrese el nombre del curso 1: comunicacion
Ingrese el nombre del curso 2: matematica
Ingrese el nombre del curso 3: fisica
Ingrese su nota de curso 'comunicacion': 13
Ingrese su nota de curso 'matematica': 09
Ingrese su nota de curso 'fisica': 10

Cursos desaprobados
     Curso  Nota
matematica   9.0
    fisica  10.0


Ejercicio 7:Escribir un programa que almacene el abecedario en una lista, elimine de la lista las letras que ocupen posiciones múltiplos de 3, y muestre por pantalla la lista resultante.

In [114]:
abecedario = [chr(i) for i in range(97, 123)]

letras_filtradas = [letra for indice, letra in enumerate(abecedario, start=1) if indice % 3 == 0]

print(", ".join(letras_filtradas))

c, f, i, l, o, r, u, x


Ejercicio 8:
Escribir un programa que pida al usuario una palabra y muestre por pantalla si es un palíndromo.

In [115]:
palabra = input("Ingrese una palabra de su agrado: ")
palabra_invertida = palabra[::-1]
if palabra == palabra_invertida:
  print(f"La palabra '{palabra}' es un palindromo")
else:
  print(f"La palabra '{palabra}' no es un palindromo")


Ingrese una palabra de su agrado: avestruz
La palabra 'avestruz' no es un palindromo


Ejercicio 9:
Escribir un programa que pida al usuario una palabra y muestre por pantalla el número de veces que contiene cada vocal.

In [116]:
palabra = input("Ingrese una palabra de su agrado: ")
vocales = "aeiou"
for vocal in vocales:
  print(f"La vocal '{vocal}' aparece {palabra.lower().count(vocal)} veces")


Ingrese una palabra de su agrado: abecedario
La vocal 'a' aparece 2 veces
La vocal 'e' aparece 2 veces
La vocal 'i' aparece 1 veces
La vocal 'o' aparece 1 veces
La vocal 'u' aparece 0 veces


Ejercicio 10:
Escribir un programa que almacene en una lista los siguientes precios, 50, 75, 46, 22, 80, 65, 8, y muestre por pantalla el menor y el mayor de los precios.

In [117]:
precios = [50, 75, 46, 22, 80, 65, 8]
print(f"El menor precio es: {min(precios)}")
print(f"El mayor precio es: {max(precios)}")

El menor precio es: 8
El mayor precio es: 80


Ejercicio 11:
Escribir un programa que almacene los vectores (1,2,3) y (-1,0,2) en dos listas y muestre por pantalla su producto escalar.

In [118]:
vector1 = [1,2,3]
vector2 = [-1,0,2]

producto_escalar = 0
for i in range(len(vector1)):
  producto_escalar += vector1[i] * vector2[i]

print(f"El producto escalar de los vectores es: {producto_escalar}")



El producto escalar de los vectores es: 5


Ejercicio 12:
Escribir un programa que almacene las matrices en una lista y muestre por pantalla su producto.

In [120]:
import numpy as np
matrices = int(input("Ingrese el numero de matrices que desea generar: "))
filas = int(input("Ingrese el numero de filas: "))
columnas = int(input("Ingrese el numero de columnas: "))

todas_matrices = []

for num_matriz in range (1, matrices+1):
  matriz = []
  for i in range (filas):
    fila=[]
    for j in range (columnas):
      valor = int(input(f"Ingrese el valor de la posicion [{i+1}][{j+1}] de la matriz {num_matriz}: "))
      fila.append(valor)
    matriz.append(fila)
  todas_matrices.append(np.array(matriz))

for idx, mat in enumerate(todas_matrices, start=1):
    print(f"\nMatriz {idx}:")
    print(mat)

producto_matrices = todas_matrices[0]
for mat in todas_matrices[1:]:
    producto_matrices = np.dot(producto_matrices, mat)

print("\nProducto de las matrices:")
print(producto_matrices)


Ingrese el numero de matrices que desea generar: 2
Ingrese el numero de filas: 2
Ingrese el numero de columnas: 2
Ingrese el valor de la posicion [1][1] de la matriz 1: 4
Ingrese el valor de la posicion [1][2] de la matriz 1: 6
Ingrese el valor de la posicion [2][1] de la matriz 1: 7
Ingrese el valor de la posicion [2][2] de la matriz 1: 8
Ingrese el valor de la posicion [1][1] de la matriz 2: 1
Ingrese el valor de la posicion [1][2] de la matriz 2: 2
Ingrese el valor de la posicion [2][1] de la matriz 2: 3
Ingrese el valor de la posicion [2][2] de la matriz 2: 4

Matriz 1:
[[4 6]
 [7 8]]

Matriz 2:
[[1 2]
 [3 4]]

Producto de las matrices:
[[22 32]
 [31 46]]


Ejercicio 13:
Escribir un programa que pregunte por una muestra de números, separados por comas, los guarde en una lista y muestre por pantalla su media y desviación típica.

In [128]:
from statistics import mean, stdev as dst

numeros = []
cantidad_num = int(input("Ingrese a cantidad de numeros que desea ingresar: "))

for i in range(1, cantidad_num+1):
  numero = int(input(f"Ingrese el número {i}: "))
  numeros.append(numero)


print(f"La media es: {mean(numeros)}")
print(f"La desviacion tipica es: {dst(numeros)}")

Ingrese a cantidad de numeros que desea ingresar: 4
Ingrese el número 1: 5
Ingrese el número 2: 7
Ingrese el número 3: 3
Ingrese el número 4: 9
La media es: 6
La desviacion tipica es: 2.581988897471611
